# Generated by Django 4.0.4 on 2022-06-14 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyCactusApp', '0003_producto_fecha_producto_stock_alter_producto_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='temperatura',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
