# Generated by Django 4.0.4 on 2022-06-14 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyCactusApp', '0004_producto_temperatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
