# Generated by Django 4.0.4 on 2022-06-14 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HappyCactusApp', '0005_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='link',
        ),
    ]
