# Generated by Django 4.0.4 on 2022-07-08 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HappyCactusApp', '0006_remove_producto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='link',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
